/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.infrastructure.persistence.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import moe.src.leyline.infrastructure.persistence.tables.Discount;
import com.masadora.shop.infrastructure.persistence.tables.records.DiscountRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class DiscountDao extends DAOImpl<DiscountRecord, moe.src.leyline.infrastructure.persistence.tables.pojos.Discount, Integer> {

    /**
     * Create a new DiscountDao without any configuration
     */
    public DiscountDao() {
        super(Discount.DISCOUNT, moe.src.leyline.infrastructure.persistence.tables.pojos.Discount.class);
    }

    /**
     * Create a new DiscountDao with an attached configuration
     */
    @Autowired
    public DiscountDao(Configuration configuration) {
        super(Discount.DISCOUNT, moe.src.leyline.infrastructure.persistence.tables.pojos.Discount.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(moe.src.leyline.infrastructure.persistence.tables.pojos.Discount object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<moe.src.leyline.infrastructure.persistence.tables.pojos.Discount> fetchById(Integer... values) {
        return fetch(Discount.DISCOUNT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public moe.src.leyline.infrastructure.persistence.tables.pojos.Discount fetchOneById(Integer value) {
        return fetchOne(Discount.DISCOUNT.ID, value);
    }

    /**
     * Fetch records that have <code>discount_rule_id IN (values)</code>
     */
    public List<moe.src.leyline.infrastructure.persistence.tables.pojos.Discount> fetchByDiscountRuleId(Integer... values) {
        return fetch(Discount.DISCOUNT.DISCOUNT_RULE_ID, values);
    }

    /**
     * Fetch records that have <code>coupon_id IN (values)</code>
     */
    public List<moe.src.leyline.infrastructure.persistence.tables.pojos.Discount> fetchByCouponId(Integer... values) {
        return fetch(Discount.DISCOUNT.COUPON_ID, values);
    }
}
