/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.infrastructure.persistence.daos;


import java.util.List;

import javax.annotation.Generated;

import moe.src.leyline.domain.Coupon;
import moe.src.leyline.infrastructure.persistence.tables.CouponTable;
import moe.src.leyline.infrastructure.persistence.tables.records.CouponRecord;
import static org.jooq.impl.DSL.using;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class CouponDao extends DAOImpl<CouponRecord, Coupon, Integer> {

    /**
     * Create a new CouponDao without any configuration
     */
    public CouponDao() {
        super(CouponTable.COUPON, Coupon.class);
    }

    /**
     * Create a new CouponDao with an attached configuration
     */
    @Autowired
    public CouponDao(Configuration configuration) {
        super(CouponTable.COUPON, Coupon.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(Coupon object) {
        return object.getDiscountRuleId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<Coupon> fetchById(Integer... values) {
        return fetch(CouponTable.COUPON.ID, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<Coupon> fetchByName(String... values) {
        return fetch(CouponTable.COUPON.NAME, values);
    }

    /**
     * Fetch records that have <code>discount_rule_id IN (values)</code>
     */
    public List<Coupon> fetchByDiscountRuleId(Integer... values) {
        return fetch(CouponTable.COUPON.DISCOUNT_RULE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>discount_rule_id = value</code>
     */
    public Coupon fetchOneByDiscountRuleId(Integer value) {
        return fetchOne(CouponTable.COUPON.DISCOUNT_RULE_ID, value);
    }

    /**
     *  Customize
     */
    public void t(){
        using(configuration());
    }
}
