/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.infrastructure.persistence.daos;


import java.util.List;

import javax.annotation.Generated;

import moe.src.leyline.domain.User;
import moe.src.leyline.infrastructure.persistence.tables.UserTable;
import moe.src.leyline.infrastructure.persistence.tables.records.UserRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UserDao extends DAOImpl<UserRecord, User, Integer> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(UserTable.USER, User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    @Autowired
    public UserDao(Configuration configuration) {
        super(UserTable.USER, User.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(User object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<User> fetchById(Integer... values) {
        return fetch(UserTable.USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public User fetchOneById(Integer value) {
        return fetchOne(UserTable.USER.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<User> fetchByName(String... values) {
        return fetch(UserTable.USER.NAME, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<User> fetchByPassword(String... values) {
        return fetch(UserTable.USER.PASSWORD, values);
    }
}
