/**
 * This class is generated by jOOQ
 */
package com.masadora.shop.infrastructure.persistence.tables.records;


import javax.annotation.Generated;

import moe.src.leyline.infrastructure.persistence.tables.OrderDetail;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderDetailRecord extends UpdatableRecordImpl<OrderDetailRecord> implements Record5<Integer, Integer, Integer, String, Integer> {

    private static final long serialVersionUID = -1138668866;

    /**
     * Setter for <code>leyline.order_detail.id</code>.
     */
    public OrderDetailRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>leyline.order_detail.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>leyline.order_detail.product_id</code>.
     */
    public OrderDetailRecord setProductId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>leyline.order_detail.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>leyline.order_detail.customer_id</code>.
     */
    public OrderDetailRecord setCustomerId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>leyline.order_detail.customer_id</code>.
     */
    public Integer getCustomerId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>leyline.order_detail.quantity</code>.
     */
    public OrderDetailRecord setQuantity(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>leyline.order_detail.quantity</code>.
     */
    public String getQuantity() {
        return (String) get(3);
    }

    /**
     * Setter for <code>leyline.order_detail.parent_order_id</code>.
     */
    public OrderDetailRecord setParentOrderId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>leyline.order_detail.parent_order_id</code>.
     */
    public Integer getParentOrderId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OrderDetail.ORDER_DETAIL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return OrderDetail.ORDER_DETAIL.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return OrderDetail.ORDER_DETAIL.CUSTOMER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return OrderDetail.ORDER_DETAIL.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return OrderDetail.ORDER_DETAIL.PARENT_ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getParentOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderDetailRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderDetailRecord value2(Integer value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderDetailRecord value3(Integer value) {
        setCustomerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderDetailRecord value4(String value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderDetailRecord value5(Integer value) {
        setParentOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderDetailRecord values(Integer value1, Integer value2, Integer value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderDetailRecord
     */
    public OrderDetailRecord() {
        super(OrderDetail.ORDER_DETAIL);
    }

    /**
     * Create a detached, initialised OrderDetailRecord
     */
    public OrderDetailRecord(Integer id, Integer productId, Integer customerId, String quantity, Integer parentOrderId) {
        super(OrderDetail.ORDER_DETAIL);

        set(0, id);
        set(1, productId);
        set(2, customerId);
        set(3, quantity);
        set(4, parentOrderId);
    }
}
