/**
 * This class is generated by jOOQ
 */
package com.masadora.shop.infrastructure.persistence.tables.records;


import javax.annotation.Generated;

import moe.src.leyline.infrastructure.persistence.tables.OrderParent;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderParentRecord extends TableRecordImpl<OrderParentRecord> implements Record1<Integer> {

    private static final long serialVersionUID = 1552259387;

    /**
     * Setter for <code>leyline.order_parent.id</code>.
     */
    public OrderParentRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>leyline.order_parent.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Integer> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Integer> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OrderParent.ORDER_PARENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderParentRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderParentRecord values(Integer value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderParentRecord
     */
    public OrderParentRecord() {
        super(OrderParent.ORDER_PARENT);
    }

    /**
     * Create a detached, initialised OrderParentRecord
     */
    public OrderParentRecord(Integer id) {
        super(OrderParent.ORDER_PARENT);

        set(0, id);
    }
}
