/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.infrastructure.persistence;


import javax.annotation.Generated;

import moe.src.leyline.infrastructure.persistence.tables.CouponTable;
import moe.src.leyline.infrastructure.persistence.tables.DiscountRuleTable;
import moe.src.leyline.infrastructure.persistence.tables.DiscountTable;
import moe.src.leyline.infrastructure.persistence.tables.OrderDetailTable;
import moe.src.leyline.infrastructure.persistence.tables.ProductTable;
import moe.src.leyline.infrastructure.persistence.tables.UserTable;
import moe.src.leyline.infrastructure.persistence.tables.records.CouponRecord;
import moe.src.leyline.infrastructure.persistence.tables.records.DiscountRecord;
import moe.src.leyline.infrastructure.persistence.tables.records.DiscountRuleRecord;
import moe.src.leyline.infrastructure.persistence.tables.records.OrderDetailRecord;
import moe.src.leyline.infrastructure.persistence.tables.records.ProductRecord;
import moe.src.leyline.infrastructure.persistence.tables.records.UserRecord;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>leyline</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CouponRecord> KEY_COUPON_PRIMARY = UniqueKeys0.KEY_COUPON_PRIMARY;
    public static final UniqueKey<DiscountRecord> KEY_DISCOUNT_PRIMARY = UniqueKeys0.KEY_DISCOUNT_PRIMARY;
    public static final UniqueKey<DiscountRuleRecord> KEY_DISCOUNT_RULE_PRIMARY = UniqueKeys0.KEY_DISCOUNT_RULE_PRIMARY;
    public static final UniqueKey<OrderDetailRecord> KEY_ORDER_DETAIL_PRIMARY = UniqueKeys0.KEY_ORDER_DETAIL_PRIMARY;
    public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = UniqueKeys0.KEY_PRODUCT_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CouponRecord, DiscountRuleRecord> COUPON_IBFK_1 = ForeignKeys0.COUPON_IBFK_1;
    public static final ForeignKey<OrderDetailRecord, ProductRecord> ORDER_DETAIL_IBFK_1 = ForeignKeys0.ORDER_DETAIL_IBFK_1;
    public static final ForeignKey<OrderDetailRecord, UserRecord> ORDER_DETAIL_IBFK_2 = ForeignKeys0.ORDER_DETAIL_IBFK_2;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CouponRecord> KEY_COUPON_PRIMARY = createUniqueKey(CouponTable.COUPON, "KEY_coupon_PRIMARY", CouponTable.COUPON.DISCOUNT_RULE_ID);
        public static final UniqueKey<DiscountRecord> KEY_DISCOUNT_PRIMARY = createUniqueKey(DiscountTable.DISCOUNT_TABLE, "KEY_discount_PRIMARY", DiscountTable.DISCOUNT_TABLE.ID);
        public static final UniqueKey<DiscountRuleRecord> KEY_DISCOUNT_RULE_PRIMARY = createUniqueKey(DiscountRuleTable.DISCOUNT_RULE, "KEY_discount_rule_PRIMARY", DiscountRuleTable.DISCOUNT_RULE.ID);
        public static final UniqueKey<OrderDetailRecord> KEY_ORDER_DETAIL_PRIMARY = createUniqueKey(OrderDetailTable.ORDER_DETAIL, "KEY_order_detail_PRIMARY", OrderDetailTable.ORDER_DETAIL.ID);
        public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = createUniqueKey(ProductTable.PRODUCT, "KEY_product_PRIMARY", ProductTable.PRODUCT.ID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = createUniqueKey(UserTable.USER, "KEY_user_PRIMARY", UserTable.USER.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<CouponRecord, DiscountRuleRecord> COUPON_IBFK_1 = createForeignKey(moe.src.leyline.infrastructure.persistence.Keys.KEY_DISCOUNT_RULE_PRIMARY, CouponTable.COUPON, "coupon_ibfk_1", CouponTable.COUPON.DISCOUNT_RULE_ID);
        public static final ForeignKey<OrderDetailRecord, ProductRecord> ORDER_DETAIL_IBFK_1 = createForeignKey(moe.src.leyline.infrastructure.persistence.Keys.KEY_PRODUCT_PRIMARY, OrderDetailTable.ORDER_DETAIL, "order_detail_ibfk_1", OrderDetailTable.ORDER_DETAIL.PRODUCT_ID);
        public static final ForeignKey<OrderDetailRecord, UserRecord> ORDER_DETAIL_IBFK_2 = createForeignKey(moe.src.leyline.infrastructure.persistence.Keys.KEY_USER_PRIMARY, OrderDetailTable.ORDER_DETAIL, "order_detail_ibfk_2", OrderDetailTable.ORDER_DETAIL.CUSTOMER_ID);
    }
}
