/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.infrastructure.persistence;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import moe.src.leyline.infrastructure.persistence.tables.CouponTable;
import moe.src.leyline.infrastructure.persistence.tables.DiscountRuleTable;
import moe.src.leyline.infrastructure.persistence.tables.DiscountTable;
import moe.src.leyline.infrastructure.persistence.tables.OrderDetailTable;
import moe.src.leyline.infrastructure.persistence.tables.OrderParentTable;
import moe.src.leyline.infrastructure.persistence.tables.ProductTable;
import moe.src.leyline.infrastructure.persistence.tables.UserTable;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Leyline extends SchemaImpl {

    private static final long serialVersionUID = 1738055920;

    /**
     * The reference instance of <code>leyline</code>
     */
    public static final Leyline LEYLINE = new Leyline();

    /**
     * The table <code>leyline.coupon</code>.
     */
    public final CouponTable COUPON = CouponTable.COUPON;

    /**
     * The table <code>leyline.discount</code>.
     */
    public final DiscountTable DISCOUNTTable = DiscountTable.DISCOUNT_TABLE;

    /**
     * The table <code>leyline.discount_rule</code>.
     */
    public final DiscountRuleTable DISCOUNT_RULE = DiscountRuleTable.DISCOUNT_RULE;

    /**
     * The table <code>leyline.order_detail</code>.
     */
    public final OrderDetailTable ORDER_DETAIL = OrderDetailTable.ORDER_DETAIL;

    /**
     * The table <code>leyline.order_parent</code>.
     */
    public final OrderParentTable ORDER_PARENT = OrderParentTable.ORDER_PARENT;

    /**
     * The table <code>leyline.product</code>.
     */
    public final ProductTable PRODUCT = ProductTable.PRODUCT;

    /**
     * The table <code>leyline.user</code>.
     */
    public final UserTable USER = UserTable.USER;

    /**
     * No further instances allowed
     */
    private Leyline() {
        super("leyline", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            CouponTable.COUPON,
            DiscountTable.DISCOUNT_TABLE,
            DiscountRuleTable.DISCOUNT_RULE,
            OrderDetailTable.ORDER_DETAIL,
            OrderParentTable.ORDER_PARENT,
            ProductTable.PRODUCT,
            UserTable.USER);
    }
}
