/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.infrastructure.persistence;


import javax.annotation.Generated;

import moe.src.leyline.infrastructure.persistence.tables.CouponTable;
import moe.src.leyline.infrastructure.persistence.tables.DiscountRuleTable;
import moe.src.leyline.infrastructure.persistence.tables.DiscountTable;
import moe.src.leyline.infrastructure.persistence.tables.OrderDetailTable;
import moe.src.leyline.infrastructure.persistence.tables.OrderParentTable;
import moe.src.leyline.infrastructure.persistence.tables.ProductTable;
import moe.src.leyline.infrastructure.persistence.tables.UserTable;

/**
 * Convenience access to all tables in leyline
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>leyline.coupon</code>.
     */
    public static final CouponTable COUPON = CouponTable.COUPON;

    /**
     * The table <code>leyline.discount</code>.
     */
    public static final DiscountTable DISCOUNT_TABLE = DiscountTable.DISCOUNT_TABLE;

    /**
     * The table <code>leyline.discount_rule</code>.
     */
    public static final DiscountRuleTable DISCOUNT_RULE = DiscountRuleTable.DISCOUNT_RULE;

    /**
     * The table <code>leyline.order_detail</code>.
     */
    public static final OrderDetailTable ORDER_DETAIL = OrderDetailTable.ORDER_DETAIL;

    /**
     * The table <code>leyline.order_parent</code>.
     */
    public static final OrderParentTable ORDER_PARENT = OrderParentTable.ORDER_PARENT;

    /**
     * The table <code>leyline.product</code>.
     */
    public static final ProductTable PRODUCT = ProductTable.PRODUCT;

    /**
     * The table <code>leyline.user</code>.
     */
    public static final UserTable USER = UserTable.USER;
}
