/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.infrastructure.persistence.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderParent implements Serializable {

    private static final long serialVersionUID = 1290279281;

    private Integer id;

    public OrderParent() {}

    public OrderParent(OrderParent value) {
        this.id = value.id;
    }

    public OrderParent(
        Integer id
    ) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public OrderParent setId(Integer id) {
        this.id = id;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrderParent (");

        sb.append(id);

        sb.append(")");
        return sb.toString();
    }
}
