/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.infrastructure.persistence;


import javax.annotation.Generated;

import moe.src.leyline.infrastructure.persistence.tables.Coupon;
import moe.src.leyline.infrastructure.persistence.tables.Discount;
import moe.src.leyline.infrastructure.persistence.tables.DiscountRule;
import moe.src.leyline.infrastructure.persistence.tables.OrderDetail;
import moe.src.leyline.infrastructure.persistence.tables.Product;
import moe.src.leyline.infrastructure.persistence.tables.User;
import com.masadora.shop.infrastructure.persistence.tables.records.CouponRecord;
import com.masadora.shop.infrastructure.persistence.tables.records.DiscountRecord;
import com.masadora.shop.infrastructure.persistence.tables.records.DiscountRuleRecord;
import com.masadora.shop.infrastructure.persistence.tables.records.OrderDetailRecord;
import com.masadora.shop.infrastructure.persistence.tables.records.ProductRecord;
import com.masadora.shop.infrastructure.persistence.tables.records.UserRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>leyline</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<OrderDetailRecord, Integer> IDENTITY_ORDER_DETAIL = Identities0.IDENTITY_ORDER_DETAIL;
    public static final Identity<ProductRecord, Integer> IDENTITY_PRODUCT = Identities0.IDENTITY_PRODUCT;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CouponRecord> KEY_COUPON_PRIMARY = UniqueKeys0.KEY_COUPON_PRIMARY;
    public static final UniqueKey<DiscountRecord> KEY_DISCOUNT_PRIMARY = UniqueKeys0.KEY_DISCOUNT_PRIMARY;
    public static final UniqueKey<DiscountRuleRecord> KEY_DISCOUNT_RULE_PRIMARY = UniqueKeys0.KEY_DISCOUNT_RULE_PRIMARY;
    public static final UniqueKey<OrderDetailRecord> KEY_ORDER_DETAIL_PRIMARY = UniqueKeys0.KEY_ORDER_DETAIL_PRIMARY;
    public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = UniqueKeys0.KEY_PRODUCT_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CouponRecord, DiscountRuleRecord> COUPON_IBFK_1 = ForeignKeys0.COUPON_IBFK_1;
    public static final ForeignKey<OrderDetailRecord, ProductRecord> ID = ForeignKeys0.ID;
    public static final ForeignKey<OrderDetailRecord, UserRecord> ORDER_DETAIL_IBFK_2 = ForeignKeys0.ORDER_DETAIL_IBFK_2;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<OrderDetailRecord, Integer> IDENTITY_ORDER_DETAIL = createIdentity(OrderDetail.ORDER_DETAIL, OrderDetail.ORDER_DETAIL.ID);
        public static Identity<ProductRecord, Integer> IDENTITY_PRODUCT = createIdentity(Product.PRODUCT, Product.PRODUCT.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CouponRecord> KEY_COUPON_PRIMARY = createUniqueKey(Coupon.COUPON, "KEY_coupon_PRIMARY", Coupon.COUPON.DISCOUNT_RULE_ID);
        public static final UniqueKey<DiscountRecord> KEY_DISCOUNT_PRIMARY = createUniqueKey(Discount.DISCOUNT, "KEY_discount_PRIMARY", Discount.DISCOUNT.ID);
        public static final UniqueKey<DiscountRuleRecord> KEY_DISCOUNT_RULE_PRIMARY = createUniqueKey(DiscountRule.DISCOUNT_RULE, "KEY_discount_rule_PRIMARY", DiscountRule.DISCOUNT_RULE.ID);
        public static final UniqueKey<OrderDetailRecord> KEY_ORDER_DETAIL_PRIMARY = createUniqueKey(OrderDetail.ORDER_DETAIL, "KEY_order_detail_PRIMARY", OrderDetail.ORDER_DETAIL.ID);
        public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = createUniqueKey(Product.PRODUCT, "KEY_product_PRIMARY", Product.PRODUCT.ID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<CouponRecord, DiscountRuleRecord> COUPON_IBFK_1 = createForeignKey(moe.src.leyline.infrastructure.persistence.Keys.KEY_DISCOUNT_RULE_PRIMARY, Coupon.COUPON, "coupon_ibfk_1", Coupon.COUPON.DISCOUNT_RULE_ID);
        public static final ForeignKey<OrderDetailRecord, ProductRecord> ID = createForeignKey(moe.src.leyline.infrastructure.persistence.Keys.KEY_PRODUCT_PRIMARY, OrderDetail.ORDER_DETAIL, "id", OrderDetail.ORDER_DETAIL.PRODUCT_ID);
        public static final ForeignKey<OrderDetailRecord, UserRecord> ORDER_DETAIL_IBFK_2 = createForeignKey(moe.src.leyline.infrastructure.persistence.Keys.KEY_USER_PRIMARY, OrderDetail.ORDER_DETAIL, "order_detail_ibfk_2", OrderDetail.ORDER_DETAIL.CUSTOMER_ID);
    }
}
