/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.domain;

import java.io.Serializable;

import javax.annotation.Generated;

import lombok.Data;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Data public class Coupon implements Serializable {

    private static final long serialVersionUID = -1953578848;

    private Integer id;
    private String  name;
    private Integer discountRuleId;

}
