/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.domain;

import java.io.Serializable;

import javax.annotation.Generated;

import lombok.Data;
import moe.src.leyline.infrastructure.tagging.DO;

@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Data public class Coupon implements DO {
    private static final long serialVersionUID = -1953578848;

    private Integer id;
    private String  name;
    private Integer discountRuleId;

}
