/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.domain;

import java.io.Serializable;

import lombok.Data;

@Data public class DiscountRule implements Serializable {

    private static final long serialVersionUID = -202101687;

    private Integer id;
    private Integer price;
    private Integer rate;

}
