/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.domain;

import java.io.Serializable;

import lombok.Data;
import moe.src.leyline.infrastructure.tagging.DO;

@Data public class Discount extends DO {

    private static final long serialVersionUID = 984377785;

    private Integer id;
    private Integer discountRuleId;
    private Integer couponId;

}
