/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.domain;

import lombok.Data;
import moe.src.leyline.infrastructure.tagging.DO;

import java.io.Serializable;

@Data public class OrderParent implements DO {

    private static final long serialVersionUID = 1290279281;

    private Integer id;


}
