/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.domain;

import java.io.Serializable;

import lombok.Data;
import moe.src.leyline.infrastructure.tagging.DO;

@Data public class Product extends DO {

    private static final long serialVersionUID = 2018549294;

    private Integer id;
    private String  name;
    private Double  price;

}
