/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.domain;

import java.io.Serializable;

import lombok.Data;

@Data public class Product implements Serializable {

    private static final long serialVersionUID = 2018549294;

    private Integer id;
    private String  name;
    private Double  price;

}
