/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.domain;

import java.io.Serializable;

import lombok.Data;
import moe.src.leyline.infrastructure.tagging.DO;

@Data public class User implements DO {

    private static final long serialVersionUID = -1406034540;

    private Integer id;
    private String  name;
    private String  password;

}
