/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.infrastructure.persistence.tables.records;


import javax.annotation.Generated;

import moe.src.leyline.infrastructure.persistence.tables.DiscountRuleTable;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiscountRuleRecord extends UpdatableRecordImpl<DiscountRuleRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1375847722;

    /**
     * Setter for <code>leyline.discount_rule.id</code>.
     */
    public DiscountRuleRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>leyline.discount_rule.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>leyline.discount_rule.price</code>.
     */
    public DiscountRuleRecord setPrice(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>leyline.discount_rule.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>leyline.discount_rule.rate</code>.
     */
    public DiscountRuleRecord setRate(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>leyline.discount_rule.rate</code>.
     */
    public Integer getRate() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DiscountRuleTable.DISCOUNT_RULE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DiscountRuleTable.DISCOUNT_RULE.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return DiscountRuleTable.DISCOUNT_RULE.RATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiscountRuleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiscountRuleRecord value2(Integer value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiscountRuleRecord value3(Integer value) {
        setRate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiscountRuleRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DiscountRuleRecord
     */
    public DiscountRuleRecord() {
        super(DiscountRuleTable.DISCOUNT_RULE);
    }

    /**
     * Create a detached, initialised DiscountRuleRecord
     */
    public DiscountRuleRecord(Integer id, Integer price, Integer rate) {
        super(DiscountRuleTable.DISCOUNT_RULE);

        set(0, id);
        set(1, price);
        set(2, rate);
    }
}
