/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.infrastructure.persistence.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import moe.src.leyline.infrastructure.persistence.Keys;
import moe.src.leyline.infrastructure.persistence.Leyline;
import moe.src.leyline.infrastructure.persistence.tables.records.CouponRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CouponTable extends TableImpl<CouponRecord> {

    private static final long serialVersionUID = -1049729837;

    /**
     * The reference instance of <code>leyline.coupon</code>
     */
    public static final CouponTable COUPON = new CouponTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CouponRecord> getRecordType() {
        return CouponRecord.class;
    }

    /**
     * The column <code>leyline.coupon.id</code>.
     */
    public final TableField<CouponRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>leyline.coupon.name</code>.
     */
    public final TableField<CouponRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

    /**
     * The column <code>leyline.coupon.discount_rule_id</code>.
     */
    public final TableField<CouponRecord, Integer> DISCOUNT_RULE_ID = createField("discount_rule_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>leyline.coupon</code> table reference
     */
    public CouponTable() {
        this("coupon", null);
    }

    /**
     * Create an aliased <code>leyline.coupon</code> table reference
     */
    public CouponTable(String alias) {
        this(alias, COUPON);
    }

    private CouponTable(String alias, Table<CouponRecord> aliased) {
        this(alias, aliased, null);
    }

    private CouponTable(String alias, Table<CouponRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Leyline.LEYLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CouponRecord> getPrimaryKey() {
        return Keys.KEY_COUPON_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CouponRecord>> getKeys() {
        return Arrays.<UniqueKey<CouponRecord>>asList(Keys.KEY_COUPON_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CouponRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CouponRecord, ?>>asList(Keys.COUPON_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CouponTable as(String alias) {
        return new CouponTable(alias, this);
    }

    /**
     * Rename this table
     */
    public CouponTable rename(String name) {
        return new CouponTable(name, null);
    }
}
