/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.infrastructure.persistence.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import moe.src.leyline.infrastructure.persistence.Keys;
import moe.src.leyline.infrastructure.persistence.Leyline;
import moe.src.leyline.infrastructure.persistence.tables.records.DiscountRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Discount extends TableImpl<DiscountRecord> {

    private static final long serialVersionUID = 629487998;

    /**
     * The reference instance of <code>leyline.discount</code>
     */
    public static final Discount DISCOUNT = new Discount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DiscountRecord> getRecordType() {
        return DiscountRecord.class;
    }

    /**
     * The column <code>leyline.discount.id</code>.
     */
    public final TableField<DiscountRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>leyline.discount.discount_rule_id</code>.
     */
    public final TableField<DiscountRecord, Integer> DISCOUNT_RULE_ID = createField("discount_rule_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>leyline.discount.coupon_id</code>.
     */
    public final TableField<DiscountRecord, Integer> COUPON_ID = createField("coupon_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>leyline.discount</code> table reference
     */
    public Discount() {
        this("discount", null);
    }

    /**
     * Create an aliased <code>leyline.discount</code> table reference
     */
    public Discount(String alias) {
        this(alias, DISCOUNT);
    }

    private Discount(String alias, Table<DiscountRecord> aliased) {
        this(alias, aliased, null);
    }

    private Discount(String alias, Table<DiscountRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Leyline.LEYLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DiscountRecord> getPrimaryKey() {
        return Keys.KEY_DISCOUNT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DiscountRecord>> getKeys() {
        return Arrays.<UniqueKey<DiscountRecord>>asList(Keys.KEY_DISCOUNT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Discount as(String alias) {
        return new Discount(alias, this);
    }

    /**
     * Rename this table
     */
    public Discount rename(String name) {
        return new Discount(name, null);
    }
}
