/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.infrastructure.persistence.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import moe.src.leyline.infrastructure.persistence.Keys;
import moe.src.leyline.infrastructure.persistence.Leyline;
import moe.src.leyline.infrastructure.persistence.tables.records.DiscountRuleRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiscountRuleTable extends TableImpl<DiscountRuleRecord> {

    private static final long serialVersionUID = -1879894900;

    /**
     * The reference instance of <code>leyline.discount_rule</code>
     */
    public static final DiscountRuleTable DISCOUNT_RULE = new DiscountRuleTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DiscountRuleRecord> getRecordType() {
        return DiscountRuleRecord.class;
    }

    /**
     * The column <code>leyline.discount_rule.id</code>.
     */
    public final TableField<DiscountRuleRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>leyline.discount_rule.price</code>.
     */
    public final TableField<DiscountRuleRecord, Integer> PRICE = createField("price", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>leyline.discount_rule.rate</code>.
     */
    public final TableField<DiscountRuleRecord, Integer> RATE = createField("rate", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>leyline.discount_rule</code> table reference
     */
    public DiscountRuleTable() {
        this("discount_rule", null);
    }

    /**
     * Create an aliased <code>leyline.discount_rule</code> table reference
     */
    public DiscountRuleTable(String alias) {
        this(alias, DISCOUNT_RULE);
    }

    private DiscountRuleTable(String alias, Table<DiscountRuleRecord> aliased) {
        this(alias, aliased, null);
    }

    private DiscountRuleTable(String alias, Table<DiscountRuleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Leyline.LEYLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DiscountRuleRecord> getPrimaryKey() {
        return Keys.KEY_DISCOUNT_RULE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DiscountRuleRecord>> getKeys() {
        return Arrays.<UniqueKey<DiscountRuleRecord>>asList(Keys.KEY_DISCOUNT_RULE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiscountRuleTable as(String alias) {
        return new DiscountRuleTable(alias, this);
    }

    /**
     * Rename this table
     */
    public DiscountRuleTable rename(String name) {
        return new DiscountRuleTable(name, null);
    }
}
