/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.infrastructure.persistence.tables;


import javax.annotation.Generated;

import moe.src.leyline.infrastructure.persistence.Leyline;
import moe.src.leyline.infrastructure.persistence.tables.records.OrderParentRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderParent extends TableImpl<OrderParentRecord> {

    private static final long serialVersionUID = -1675957550;

    /**
     * The reference instance of <code>leyline.order_parent</code>
     */
    public static final OrderParent ORDER_PARENT = new OrderParent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderParentRecord> getRecordType() {
        return OrderParentRecord.class;
    }

    /**
     * The column <code>leyline.order_parent.id</code>.
     */
    public final TableField<OrderParentRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>leyline.order_parent</code> table reference
     */
    public OrderParent() {
        this("order_parent", null);
    }

    /**
     * Create an aliased <code>leyline.order_parent</code> table reference
     */
    public OrderParent(String alias) {
        this(alias, ORDER_PARENT);
    }

    private OrderParent(String alias, Table<OrderParentRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrderParent(String alias, Table<OrderParentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Leyline.LEYLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderParent as(String alias) {
        return new OrderParent(alias, this);
    }

    /**
     * Rename this table
     */
    public OrderParent rename(String name) {
        return new OrderParent(name, null);
    }
}
