/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.infrastructure.persistence.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import moe.src.leyline.infrastructure.persistence.tables.Product;
import moe.src.leyline.infrastructure.persistence.tables.records.ProductRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ProductDao extends DAOImpl<ProductRecord, moe.src.leyline.infrastructure.persistence.tables.pojos.Product, Integer> {

    /**
     * Create a new ProductDao without any configuration
     */
    public ProductDao() {
        super(Product.PRODUCT, moe.src.leyline.infrastructure.persistence.tables.pojos.Product.class);
    }

    /**
     * Create a new ProductDao with an attached configuration
     */
    @Autowired
    public ProductDao(Configuration configuration) {
        super(Product.PRODUCT, moe.src.leyline.infrastructure.persistence.tables.pojos.Product.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(moe.src.leyline.infrastructure.persistence.tables.pojos.Product object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<moe.src.leyline.infrastructure.persistence.tables.pojos.Product> fetchById(Integer... values) {
        return fetch(Product.PRODUCT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public moe.src.leyline.infrastructure.persistence.tables.pojos.Product fetchOneById(Integer value) {
        return fetchOne(Product.PRODUCT.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<moe.src.leyline.infrastructure.persistence.tables.pojos.Product> fetchByName(String... values) {
        return fetch(Product.PRODUCT.NAME, values);
    }

    /**
     * Fetch records that have <code>price IN (values)</code>
     */
    public List<moe.src.leyline.infrastructure.persistence.tables.pojos.Product> fetchByPrice(Double... values) {
        return fetch(Product.PRODUCT.PRICE, values);
    }
}
