/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.infrastructure.persistence.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Coupon implements Serializable {

    private static final long serialVersionUID = -1953578848;

    private Integer id;
    private String  name;
    private Integer discountRuleId;

    public Coupon() {}

    public Coupon(Coupon value) {
        this.id = value.id;
        this.name = value.name;
        this.discountRuleId = value.discountRuleId;
    }

    public Coupon(
        Integer id,
        String  name,
        Integer discountRuleId
    ) {
        this.id = id;
        this.name = name;
        this.discountRuleId = discountRuleId;
    }

    public Integer getId() {
        return this.id;
    }

    public Coupon setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Coupon setName(String name) {
        this.name = name;
        return this;
    }

    public Integer getDiscountRuleId() {
        return this.discountRuleId;
    }

    public Coupon setDiscountRuleId(Integer discountRuleId) {
        this.discountRuleId = discountRuleId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Coupon (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(discountRuleId);

        sb.append(")");
        return sb.toString();
    }
}
