/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.infrastructure.persistence.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiscountRule implements Serializable {

    private static final long serialVersionUID = -202101687;

    private Integer id;
    private Integer price;
    private Integer rate;

    public DiscountRule() {}

    public DiscountRule(DiscountRule value) {
        this.id = value.id;
        this.price = value.price;
        this.rate = value.rate;
    }

    public DiscountRule(
        Integer id,
        Integer price,
        Integer rate
    ) {
        this.id = id;
        this.price = price;
        this.rate = rate;
    }

    public Integer getId() {
        return this.id;
    }

    public DiscountRule setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getPrice() {
        return this.price;
    }

    public DiscountRule setPrice(Integer price) {
        this.price = price;
        return this;
    }

    public Integer getRate() {
        return this.rate;
    }

    public DiscountRule setRate(Integer rate) {
        this.rate = rate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DiscountRule (");

        sb.append(id);
        sb.append(", ").append(price);
        sb.append(", ").append(rate);

        sb.append(")");
        return sb.toString();
    }
}
