/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.infrastructure.persistence.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Discount implements Serializable {

    private static final long serialVersionUID = 984377785;

    private Integer id;
    private Integer discountRuleId;
    private Integer couponId;

    public Discount() {}

    public Discount(Discount value) {
        this.id = value.id;
        this.discountRuleId = value.discountRuleId;
        this.couponId = value.couponId;
    }

    public Discount(
        Integer id,
        Integer discountRuleId,
        Integer couponId
    ) {
        this.id = id;
        this.discountRuleId = discountRuleId;
        this.couponId = couponId;
    }

    public Integer getId() {
        return this.id;
    }

    public Discount setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getDiscountRuleId() {
        return this.discountRuleId;
    }

    public Discount setDiscountRuleId(Integer discountRuleId) {
        this.discountRuleId = discountRuleId;
        return this;
    }

    public Integer getCouponId() {
        return this.couponId;
    }

    public Discount setCouponId(Integer couponId) {
        this.couponId = couponId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Discount (");

        sb.append(id);
        sb.append(", ").append(discountRuleId);
        sb.append(", ").append(couponId);

        sb.append(")");
        return sb.toString();
    }
}
