/**
 * This class is generated by jOOQ
 */
package moe.src.leyline.infrastructure.persistence.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderDetail implements Serializable {

    private static final long serialVersionUID = -325383597;

    private Integer id;
    private Integer productId;
    private Integer customerId;
    private String  quantity;
    private Integer parentOrderId;

    public OrderDetail() {}

    public OrderDetail(OrderDetail value) {
        this.id = value.id;
        this.productId = value.productId;
        this.customerId = value.customerId;
        this.quantity = value.quantity;
        this.parentOrderId = value.parentOrderId;
    }

    public OrderDetail(
        Integer id,
        Integer productId,
        Integer customerId,
        String  quantity,
        Integer parentOrderId
    ) {
        this.id = id;
        this.productId = productId;
        this.customerId = customerId;
        this.quantity = quantity;
        this.parentOrderId = parentOrderId;
    }

    public Integer getId() {
        return this.id;
    }

    public OrderDetail setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getProductId() {
        return this.productId;
    }

    public OrderDetail setProductId(Integer productId) {
        this.productId = productId;
        return this;
    }

    public Integer getCustomerId() {
        return this.customerId;
    }

    public OrderDetail setCustomerId(Integer customerId) {
        this.customerId = customerId;
        return this;
    }

    public String getQuantity() {
        return this.quantity;
    }

    public OrderDetail setQuantity(String quantity) {
        this.quantity = quantity;
        return this;
    }

    public Integer getParentOrderId() {
        return this.parentOrderId;
    }

    public OrderDetail setParentOrderId(Integer parentOrderId) {
        this.parentOrderId = parentOrderId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrderDetail (");

        sb.append(id);
        sb.append(", ").append(productId);
        sb.append(", ").append(customerId);
        sb.append(", ").append(quantity);
        sb.append(", ").append(parentOrderId);

        sb.append(")");
        return sb.toString();
    }
}
